# Generated by Django 6.0.6 on 2026-07-06 11:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inspection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NTESCoach",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("coach_sequence", models.PositiveIntegerField()),
                ("coach_number", models.CharField(max_length=20)),
                (
                    "coach_type",
                    models.CharField(
                        help_text="Raw coach type code received from NTES.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ntes_coaches",
                        to="inspection.inspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "NTES Coach",
                "verbose_name_plural": "NTES Coaches",
                "db_table": "ntes_coach",
                "ordering": ["coach_sequence"],
            },
        ),
    ]
