# Generated by Django 6.0.6 on 2026-07-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0001_initial"),
        ("ntes", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ntescoach",
            constraint=models.UniqueConstraint(
                fields=("inspection", "coach_sequence"),
                name="unique_coach_sequence_per_inspection",
            ),
        ),
        migrations.AddConstraint(
            model_name="ntescoach",
            constraint=models.UniqueConstraint(
                fields=("inspection", "coach_number"),
                name="unique_coach_number_per_inspection",
            ),
        ),
    ]
