# Generated by Django 6.0.6 on 2026-07-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ntes", "0002_ntescoach_unique_coach_sequence_per_inspection_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ntescoach",
            name="unique_coach_number_per_inspection",
        ),
    ]
