# Generated by Django 6.0.6 on 2026-07-06 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inspection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIResultRaw",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Raw JSON payload received from the AI service."
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_results",
                        to="inspection.inspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Result",
                "verbose_name_plural": "AI Results",
                "db_table": "ai_result_raw",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["inspection"], name="ai_result_r_inspect_8adb96_idx"
                    ),
                    models.Index(
                        fields=["received_at"], name="ai_result_r_receive_bfb85d_idx"
                    ),
                ],
            },
        ),
    ]
