# Generated by Django 6.0.6 on 2026-07-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airesultraw",
            name="payload",
            field=models.JSONField(
                help_text="Immutable raw JSON payload received from the AI service. Must never be modified after creation."
            ),
        ),
    ]
