# Generated by Django 6.0.6 on 2026-07-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_alter_airesultraw_payload"),
    ]

    operations = [
        migrations.AddField(
            model_name="airesultraw",
            name="inspection_run_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="airesultraw",
            name="status",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
