# Generated by Django 6.0.6 on 2026-07-15 09:46

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_airesultraw_inspection_run_id_airesultraw_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airesultraw",
            name="payload",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Immutable raw JSON payload received from the AI service. Must never be modified after creation.",
            ),
        ),
    ]
