from io import BytesIO
import textwrap

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import Preformatted, SimpleDocTemplate

from apps.reports.dto import DailyReportDTO
from apps.reports.repositories import ReportsRepository

from apps.mapping.enums import TankDefectType

# Coaches needing cleaning: currently just "surface not clean".
# Add more types here if other defects should also trigger a cleaning flag.
CLEANING_RELATED_DEFECT_TYPES = {
    TankDefectType.SURFACE_NOT_CLEAN,
}

# None of your three current defect types are inherently safety-critical
# (they're maintenance/cleanliness issues, not structural/safety hazards).
# Leaving this empty means "No critical safety defects" will always show.
# If you want e.g. PIPE_NOT_CONNECTED to count as critical (risk of leakage
# onto tracks), add it here explicitly:
CRITICAL_DEFECT_TYPES: set[str] = set()
# Example if you decide PIPE_NOT_CONNECTED should be critical:
# CRITICAL_DEFECT_TYPES = {TankDefectType.PIPE_NOT_CONNECTED}
LINE_WIDTH = 56


def _rule(char: str) -> str:
    return char * LINE_WIDTH


def _row(label: str, value: str, label_width: int = 26) -> str:
    return f"{label.ljust(label_width)}{value}"

def _bullet_lines(text: str, width: int = LINE_WIDTH) -> list[str]:
    wrapped = textwrap.wrap(
        text,
        width=width - 2,
        initial_indent="\u2022 ",
        subsequent_indent="  ",
    )
    return wrapped or ["\u2022 "]

def _train_row(
    train_number: str,
    pit: str,
    coaches: int,
    tanks: int,
    defects: int,
) -> str:
    return (
        f"{train_number.ljust(11)}"
        f"{pit.ljust(9)}"
        f"{str(coaches).rjust(7)}"
        f"{str(tanks).rjust(12)}"
        f"{str(defects).rjust(11)}"
    )


def _defect_row(display_name: str, count: int, label_width: int = 32) -> str:
    dots = "." * max(1, label_width - len(display_name))
    return f"{display_name} {dots} {count}"


def build_daily_report_text(report: DailyReportDTO) -> str:
    lines: list[str] = []

    lines.append(_rule("="))
    lines.append("AI RAILWAY BIO-TOILET INSPECTION SYSTEM".center(LINE_WIDTH))
    lines.append("DAILY INSPECTION REPORT".center(LINE_WIDTH))
    lines.append(_rule("="))
    lines.append(f"Report Date : {report.report_date.strftime('%d %b %Y')}")
    lines.append(f"Generated At: {report.generated_at.strftime('%I:%M %p')}")
    lines.append(_rule("-"))
    lines.append("SUMMARY")
    lines.append(_rule("-"))
    lines.append(_row("Trains Inspected", str(report.summary.trains_inspected)))
    lines.append(_row("Coaches Inspected", str(report.summary.coaches_inspected)))
    lines.append(_row("Bio Tanks Checked", str(report.summary.bio_tanks_inspected)))
    lines.append(_row("Defects Found", str(report.summary.defects_found)))
    lines.append(_row("Completed", str(report.summary.completed)))
    lines.append(_rule("-"))
    lines.append("TRAIN INSPECTIONS")
    lines.append(_rule("-"))
    lines.append(
        f"{'Train'.ljust(11)}{'Pit'.ljust(9)}{'Coaches'.rjust(7)}"
        f"{'Tanks'.rjust(12)}{'Defects'.rjust(11)}"
    )

    for row in report.train_rows:
        lines.append(
            _train_row(
                row.train_number,
                row.pit_line_number,
                row.coaches,
                row.tanks,
                row.defects,
            )
        )

    lines.append(_rule("-"))
    lines.append("MOST COMMON DEFECTS")
    lines.append(_rule("-"))

    for defect in report.common_defects:
        lines.append(_defect_row(defect.display_name, defect.count))

    lines.append(_rule("-"))
    lines.append("AI OBSERVATION")
    lines.append(_rule("-"))
    lines.extend(_bullet_lines(f"{report.ai_observation.total_tanks_inspected} tanks inspected"))
    lines.extend(_bullet_lines(f"{report.ai_observation.pass_percentage}% passed inspection"))
    
    if report.ai_observation.critical_defects_found:
        lines.append(
            f"\u2022 {report.ai_observation.critical_defects_found} critical safety "
            f"defect(s) found"
        )
    else:
        lines.append("\u2022 No critical safety defects")

    if report.ai_observation.cleaning_required_coaches:
        lines.append(
            f"\u2022 Cleaning required for {report.ai_observation.cleaning_required_coaches} "
            f"coach(es)"
        )
    else:
        lines.append("\u2022 No cleaning required")

    lines.append(_rule("-"))
    lines.append("Generated by AI Railway Bio-Toilet Inspection System")

    return "\n".join(lines)

from apps.reports.dto import MonthlyReportDTO, WeeklyReportDTO


def build_weekly_report_text(report: WeeklyReportDTO) -> str:
    lines: list[str] = []

    lines.append(_rule("="))
    lines.append("WEEKLY REPORT".center(LINE_WIDTH))
    lines.append(_rule("="))
    lines.append("Week")
    lines.append(
        f"{report.week_start.strftime('%d %b')} - "
        f"{report.week_end.strftime('%d %b')}"
    )
    lines.append(_rule("-"))
    lines.append(f"{'DAY'.ljust(15)}{'TRAINS'.rjust(10)}{'DEFECTS'.rjust(12)}")

    for row in report.daily_breakdown:
        lines.append(
            f"{row.day_label.ljust(15)}"
            f"{str(row.trains).rjust(10)}"
            f"{str(row.defects).rjust(12)}"
        )

    lines.append(_rule("-"))
    lines.append("Weekly Totals")
    lines.append(_row("Total Trains", str(report.totals.total_trains)))
    lines.append(_row("Total Coaches", str(report.totals.total_coaches)))
    lines.append(_row("Total Tanks", str(report.totals.total_tanks)))
    lines.append(
        _row(
            "Average Defects/Train",
            str(report.totals.average_defects_per_train),
        )
    )
    lines.append(_rule("-"))
    lines.append("Top Defects")
    lines.append(_rule("-"))

    for defect in report.top_defects:
        lines.append(_defect_row(defect.display_name, defect.count))

    lines.append(_rule("-"))
    lines.append("AI Analysis")
    lines.append(_rule("-"))

    for observation in report.ai_analysis:
        lines.extend(_bullet_lines(observation))

    lines.append(_rule("-"))
    lines.append("Generated by AI Railway Bio-Toilet Inspection System")

    return "\n".join(lines)


def build_monthly_report_text(report: MonthlyReportDTO) -> str:
    lines: list[str] = []

    lines.append(_rule("="))
    lines.append("MONTHLY REPORT".center(LINE_WIDTH))
    lines.append(_rule("="))
    lines.append("Month")
    lines.append(report.month_label)
    lines.append(_rule("-"))
    lines.append("Overview")
    lines.append(
        _row("Trains Inspected", str(report.overview.trains_inspected))
    )
    lines.append(_row("Coaches", str(report.overview.coaches_inspected)))
    lines.append(_row("Bio Tanks", str(report.overview.bio_tanks_inspected)))
    lines.append(_row("Completed", str(report.overview.completed)))
    lines.append(
        _row(
            "Average Defects",
            str(report.overview.average_defects_per_train),
        )
    )
    lines.append(_rule("-"))
    lines.append("Weekly Comparison")

    for week in report.weekly_comparison:
        lines.append(
            _row(
                week.week_label,
                f"{week.trains} trains, {week.defects} defects",
            )
        )

    lines.append(_rule("-"))
    lines.append("Most Frequent Defects")
    lines.append(_rule("-"))

    for defect in report.most_frequent_defects:
        lines.append(_defect_row(defect.display_name, defect.count))

    lines.append(_rule("-"))
    lines.append("Pit Line Performance")

    for pit in report.pit_line_performance:
        lines.append(
            _row(
                pit.pit_line_number,
                f"{pit.inspections} inspections, {pit.defects} defects "
                f"({pit.average_defects_per_inspection}/inspection)",
            )
        )

    lines.append(_rule("-"))
    lines.append("AI Recommendations")
    lines.append(_rule("-"))

    for recommendation in report.ai_recommendations:
        lines.extend(_bullet_lines(recommendation))

    lines.append(_rule("-"))
    lines.append("Generated by AI Railway Bio-Toilet Inspection System")

    return "\n".join(lines)


class ExportService:
    VALID_TYPES = {
        "daily",
        "weekly",
        "monthly",
    }

    def __init__(
        self,
        *,
        repository: ReportsRepository | None = None,
    ) -> None:
        self._repository = repository or ReportsRepository()

    def export(
        self,
        *,
        report_type: str,
    ) -> bytes:
        if report_type not in self.VALID_TYPES:
            raise ValueError(f"Unsupported report type: {report_type}.")

        if report_type == "daily":
            text = build_daily_report_text(
                self._repository.get_daily_report(),
            )
        elif report_type == "weekly":
            text = build_weekly_report_text(
                self._repository.get_weekly_report(),
            )
        else:
            text = build_monthly_report_text(
                self._repository.get_monthly_report(),
            )

        buffer = BytesIO()

        document = SimpleDocTemplate(
            buffer,
            pagesize=letter,
        )

        mono_style = ParagraphStyle(
            name="Monospace",
            fontName="Courier",
            fontSize=9,
            leading=12,
        )

        story = [Preformatted(text, mono_style)]

        document.build(story)

        pdf = buffer.getvalue()
        buffer.close()

        return pdf

