# Generated by Django 6.0.6 on 2026-07-06 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inspection", "0001_initial"),
        ("ntes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("physical_sequence", models.PositiveIntegerField()),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("MATCHED", "Matched"),
                            ("UNMATCHED", "Unmatched"),
                            ("MANUAL", "Manual"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "coach_inspection_status",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("DEFECT", "Defect"),
                            ("PARTIAL", "Partial"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaches",
                        to="inspection.inspection",
                    ),
                ),
                (
                    "ntes_coach",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapped_coach",
                        to="ntes.ntescoach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach",
                "verbose_name_plural": "Coaches",
                "db_table": "coach",
                "ordering": ["physical_sequence"],
            },
        ),
    ]
