# Generated by Django 6.0.6 on 2026-07-09 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inspection", "0001_initial"),
        ("ntes", "0002_ntescoach_unique_coach_sequence_per_inspection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "inspection_sequence",
                    models.PositiveIntegerField(
                        help_text="Coach sequence used for this inspection after the Mapping Engine applies pit-line direction and mapping rules."
                    ),
                ),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("MATCHED", "Matched"),
                            ("UNMATCHED", "Unmatched"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "coach_inspection_status",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("DEFECT", "Defect")],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaches",
                        to="inspection.inspection",
                    ),
                ),
                (
                    "ntes_coach",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapped_coach",
                        to="ntes.ntescoach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach",
                "verbose_name_plural": "Coaches",
                "db_table": "coach",
                "ordering": ["inspection_sequence"],
            },
        ),
        migrations.CreateModel(
            name="Tank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tank_identifier",
                    models.CharField(
                        help_text="Globally unique tank identifier returned by the AI (e.g. L32, R15).",
                        max_length=20,
                    ),
                ),
                (
                    "camera",
                    models.CharField(
                        choices=[("LEFT", "Left"), ("RIGHT", "Right")], max_length=5
                    ),
                ),
                (
                    "timestamp_seconds",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Timestamp (in seconds) within the inspection video.",
                        max_digits=10,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, help_text="AI confidence score.", max_digits=5
                    ),
                ),
                (
                    "evidence_image_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the AI-generated evidence image.",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanks",
                        to="mapping.coach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tank",
                "verbose_name_plural": "Tanks",
                "db_table": "tank",
                "ordering": ["tank_identifier"],
            },
        ),
        migrations.CreateModel(
            name="TankDefect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "defect_type",
                    models.CharField(
                        help_text="Raw defect label returned by the AI service.",
                        max_length=100,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="AI confidence score for the detected defect.",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defects",
                        to="mapping.tank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tank Defect",
                "verbose_name_plural": "Tank Defects",
                "db_table": "tank_defect",
                "ordering": ["id", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="coach",
            constraint=models.UniqueConstraint(
                fields=("inspection", "inspection_sequence"),
                name="unique_inspection_sequence_per_inspection",
            ),
        ),
        migrations.AddConstraint(
            model_name="tank",
            constraint=models.UniqueConstraint(
                fields=("tank_identifier",), name="unique_tank_identifier"
            ),
        ),
        migrations.AddConstraint(
            model_name="tankdefect",
            constraint=models.UniqueConstraint(
                fields=("tank", "defect_type"), name="unique_defect_per_tank"
            ),
        ),
    ]
