# Generated by Django 6.0.6 on 2026-07-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tank",
            name="unique_tank_identifier",
        ),
        migrations.AddConstraint(
            model_name="tank",
            constraint=models.UniqueConstraint(
                fields=("coach", "tank_identifier"),
                name="unique_tank_identifier_per_coach",
            ),
        ),
    ]
