# Generated by Django 6.0.6 on 2026-07-06 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tank_index",
                    models.PositiveIntegerField(
                        help_text="Global tank index assigned by the AI for the entire inspection. Uniqueness is enforced by the Mapping Engine."
                    ),
                ),
                (
                    "camera",
                    models.CharField(
                        choices=[("LEFT", "Left"), ("RIGHT", "Right")], max_length=5
                    ),
                ),
                (
                    "timestamp_seconds",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Timestamp (in seconds) within the inspection video.",
                        max_digits=10,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, help_text="AI confidence score.", max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanks",
                        to="mapping.coach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tank",
                "verbose_name_plural": "Tanks",
                "db_table": "tank",
                "ordering": ["tank_index"],
            },
        ),
    ]
