# Generated by Django 6.0.6 on 2026-07-06 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0002_tank"),
    ]

    operations = [
        migrations.CreateModel(
            name="TankDefect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "defect_type",
                    models.CharField(
                        help_text="Raw defect label returned by the AI service.",
                        max_length=100,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="AI confidence score for the detected defect.",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defects",
                        to="mapping.tank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tank Defect",
                "verbose_name_plural": "Tank Defects",
                "db_table": "tank_defect",
                "ordering": ["id"],
            },
        ),
    ]
