# Generated by Django 6.0.6 on 2026-07-06 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("train_number", models.CharField(max_length=20)),
                ("pit_line_number", models.CharField(max_length=20)),
                (
                    "inspection_time",
                    models.DateTimeField(
                        help_text="Timestamp when the inspection session begins."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_coaches", models.PositiveIntegerField(default=0)),
                ("total_tanks", models.PositiveIntegerField(default=0)),
                ("total_defected_tanks", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inspection",
                "verbose_name_plural": "Inspections",
                "db_table": "inspection",
                "ordering": ["-created_at"],
            },
        ),
    ]
