# Generated by Django 6.0.6 on 2026-07-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0002_inspection_train_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="train_name",
            field=models.CharField(
                blank=True,
                help_text="Train name retrieved from NTES at the time of inspection creation.",
                max_length=225,
                null=True,
            ),
        ),
    ]
