# Generated by Django 6.0.6 on 2026-07-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0003_alter_inspection_train_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="train_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
