# Generated by Django 6.0.6 on 2026-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0004_alter_inspection_train_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCANNING", "Scanning"),
                    ("AWAITING_TRAIN_NUMBER", "Awaiting Train Number"),
                    ("MAPPING", "Mapping"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="AWAITING_TRAIN_NUMBER",
                max_length=50,
            ),
        ),
    ]
