# Generated by Django 6.0.6 on 2026-07-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0007_alter_inspection_total_coaches"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="ntes_total_coaches",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Train's actual coach count from NTES composition. Null until a train number is confirmed.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="total_coaches",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
